### ISSUE TITLE
Remove or lower the Mobile User penalty for servers

### ISSUE THREAD

**Issue by IhrFussel** [minetest/serverlist#17]
The code that differs between "real" users and "guests" is obsolete now.

1. Back in the day when clients used "Guest" as name it made sense, but now with the new app prefixes that are TOTALLY random, you determine many users as "guests" when they are actual players that simply use such an app that gives them the prefix.

The players mostly have NO CHOICE ... the app gives them the name by default and sometimes they even have to pay to enter a custom name.

I don't think it is FAIR to count those people as "guests".

2. Because of this server list algorithm the servers JUMP many places at once cause they sometimes get more players with such prefix names and other times less of them.

**This is not something the server owner can control or decide**

Server owners are not happy about the fact that their server rank in the list is largely dependend on the amount of "guests".

3. I don't think Minetest ever had "guest accounts" ... what I understand under a guest account is something that will get created when the user joins and DELETES ITSELF as soon as the user leaves again. This kind of account is nowhere to be found in Minetest. EVERY account is the SAME.

EDIT: If the majority of core devs disagrees with removing this penalty at least consider lowering the penalty for users with these prefixes.

**Comment by sfan5** [comment]
IRC discussion: http://irc.minetest.net/minetest-hub/2017-08-08#i_5037037

**Comment by paramat** [comment]
Number of players doesn't indicate server quality to me, it just indicates number of players, so i don't see list ranking as meaning anything other than number of players. So personally i wouldn't choose to count mobile / guest players any differently for list ranking.

There is a danger that more popular servers go to the top, are seen more, and are considered to have more potential dueto player number, so more join them, keeping them at the top and hiding other servers lower down.

My thoughts are: how do we sort the list? Maybe in a neutral way but a way that shifts them around to give all servers the same exposure near the top.

**Comment by Ezhh** [comment]
@paramat I'm for fairness, but all servers do not deserve an equal time at the top. A minetesthosting server with 4 players max, only MTG mods, and no long term stability simply does not deserve to get that recognition. 

We want to showcase quality servers at the top, since those are the servers new people join. Those are the servers people use when deciding if MT is a game worth sticking with. 

The only question is how to judge quality fairly.

**Comment by paramat** [comment]
Yes i'm now thinking there has to be some kind of quality sorting. I do think mobile users should not be scored differently.

**Comment by Ezhh** [comment]
Can this please be looked at? 

I want to allow app users to play on my server so long as I have capacity for them and it hurts no one, but by doing so my position on the list frequently plummets, lowering my chances of attracting the type of players my server actually exists for as well. 

If I have 20+ players signed in (and no lag issues, good up time, and 10+ slots still available for more players), I should not find myself ranking below servers with only 5 or 6 players signed in. Yet this is what's happening.

**Comment by rubenwardy** [comment]
:+1:

I suggest reducing the penalty to 1/2 or above. Adding reliable tracking of server age would also be a plus

**Comment by sorcerykid** [comment]
There are many times that my server peaks at 40-50 players yet is ranked at the bottom of the server list, below 200+ other servers for no other reason than because I choose to cater to mobile players. 

Somehow that doesn't seem at all logical. In a day and age when mobile gaming is on the rise, the Minetest server list specifically penalizes servers that attempt to be mobile-device friendly?

![image](https://user-images.githubusercontent.com/24327224/39398957-26cc142a-4adb-11e8-9525-7234b9c87b69.png)
![image](https://user-images.githubusercontent.com/24327224/39398969-5b3db48e-4adb-11e8-9063-d5f1418da963.png)
![image](https://user-images.githubusercontent.com/24327224/39398979-723b44da-4adb-11e8-9474-3230ba69faaa.png)
![image](https://user-images.githubusercontent.com/24327224/39398992-be6f80f0-4adb-11e8-86fb-d0dd05cb583b.png)
![image](https://user-images.githubusercontent.com/24327224/39398998-ca349498-4adb-11e8-8f73-48c7dcc6b2da.png)
![image](https://user-images.githubusercontent.com/24327224/39399001-d181574a-4adb-11e8-8d9b-54076523b0b2.png)
![image](https://user-images.githubusercontent.com/24327224/39399009-e85a97e2-4adb-11e8-8ebe-be9a709c5d89.png)
![image](https://user-images.githubusercontent.com/24327224/39399016-faa5cc00-4adb-11e8-952a-029ee295dad5.png)
![image](https://user-images.githubusercontent.com/24327224/39399019-029e21e6-4adc-11e8-8ea9-9439bd748faa.png)

**Comment by git512** [comment]
While I agree mobile users tend to be of lower quality, this is by far the most asinine ranking idea I've ever heard of. I picked a username that fits the regex as the server owner account not knowing that there was extreme prejudice against having even one user that fits that pattern.  Have you never looked at a large username list? This will hit on so many PC users that it would be obvious that it is a terrible idea.  Whats more, is minetest not designed to be an open game framework? Not all "great servers" are even going to be about building nice things, nor are we going to agree what is "great".  De-ranking servers because of personal preference of play/player type is antithetical to what minetest is about.  Server uptime is a better indicator of "server quality", otherwise let the server owners do as they see fit,

**Comment by sfan5** [comment]
> Have you never looked at a large username list? This will hit on so many PC users that it would be obvious that it is a terrible idea.

Yes, it was first thing I did while refining the regex.

Here are the players which are considered "guests" from the top 15 servers. I've marked 5 players (out of 56) that looks like false-positives to me.
Not good enough?
<pre>
Emmy643
Andera649
Carlota341
Landes849
Northcraft798
Parikh119
Minelli277
Clarisa894
Rastegar481
Iliffe704
Levans215
Alissa712
Robaina339
Mcgath957
Hannig234
Frieden967
Caliendo606  <---
Papitto800  <---
Gunning379
Mallas760
Candido304
Adara851
Stowers880
Schmelmer510
Cataldi579
Roza568
Ledlow792
Sudweeks462
Bottex598
Jesse5555  <---
Hoffses844
Knickrehm856
Kostecki813
Plemmons646
Waninger689
Messler693
Degroot354
Melvina534
Greenweig165
Demesa458
Santella891
Mckissic191
Warmington451
Mccleery866
Stickman301  <---
Rowlison626
Nagase696
Heddi638
Winslett387
Hornberg609
Meroslav111  <---
Klempa267
Marcia451
Sallyann306
Vellutini231
Yannucci272
</pre>

> Server uptime is a better indicator of "server quality".

Player count is not the only criteria, things like server uptime, ping or age are considered too.

**Comment by git512** [comment]
I understand it is not the only criteria but it is the highest weighted statistic. While low quality users can be useless all the way to downright annoying it's much more frustrating to find your server unfairly deranked to suit the discrimination based on a name pattern. Especially one that would take hours of work to resolve because it requires changing literally EVERYTHING your main character has done because you were in the unlucky 10% that got hit on a false positive. And yes 10 percent is wayyyyyy to much. Can you imagine if 10% of all your emails were spam filtered incorrectly. Or if your website lost all it's search rankings because a few of your users had numbers after their names and google didn't like that.  Or if your forum posts didn't go to the top because you have 5 at the end of your username.  This is literally dictatorial control over the minetest playing community as a whole.  Many websites along the internet even recommend usernames with 3 number suffixes when the original name is taken.  And again, a "great server" is personal opinion. You very well may be significantly harming minetests popularity.

You may want to look up the 3/5ths rule. This really sounds like a modern day version of it. Deeming certain people less worthy as humans because of a visible characteristic because that characteristic is deemed by someone in power as "undesirable".  Statistics could show both groups as more likely to be of lower value. Doesn't mean it's right to use that criteria to discriminate.

Also since some servers cater specifically to mobile, who has the right to say they are less worthy of respect for how many users they have attracted to continue playing minetest.  Mobile gaming is now and the future, don't make minetest suffer obsolescence for your personal preferences. If you don't like that regex in username, ban them from your servers, but don't punish other server owners because our vision doesn't match yours on a game designed entirely on the idea of open play and open game mechanics. 

I do apologize for the tirade but to find out my work is devalued because of numbers at the end of my username is absolutely infuriating, as it very well should be.

**Comment by git512** [comment]
To add in some statistics of my own:

> Whiskey                18998
Sparkie                17942
VimaesoH86             14936
Tink67                 12475
personaone             12036
Moana                   8397
Saund                   7843
MaRTIn99                6222
Buttery123              5832
fel                     4498

These are the top 10 block placers on my server.  These are people that have built nice things.  Because of this regex matching 40% of them would be deranking my server. Almost HALF. And this is a good idea? Given that almost half of the "desirable players" I have would fit your regex, this is probably harming the minetest community as a whole.

**Comment by sfan5** [comment]
>  because you were in the unlucky 10% that got hit on a false positive

FYI neither "git512" nor "Git512" fall under the regex for guests.

> your personal preferences.
> because our vision doesn't match yours

I did not put the guest "policy" into place and neither am I the (only) one to decide about it.

> And again, a "great server" is personal opinion.

Of course, all opinions are subjective.
The opinion that is being forced on the community here is "Players that do not participate properly in the community of a server, do not create high-quality builds and/or just visit for a short-time are worth less than players that do.". Which I think is something everyone can agree on.

It also looks like you're overestimating the difference guest players make in ranking. Your server will not suddenly end up at the very bottom of the list, it will just move a few places down.
If you constantly have a modest (>10) number of active players, you can be sure to be in the top 20.

> Because of this regex matching 40% of them would be deranking my server

Wrong, the regex that is currently in use would only match one (that is `Buttery123`).

> this is probably harming the minetest community as a whole.

I'd be interested to hear why and in what way changing up server placement a bit is harming the community of Minetest players.

**Comment by git512** [comment]
Just to be clear, when I say you I am referring not to one specific individual but to the group who has decided that this is going to be and stay implemented.

No, everyone does not agree on that metric of value. A CTF server that resets the map on every round does not require "building nice things" nor long term participation.  A server about "building nice things" does. Minetest is a platform for both and more. That doesn't make the CTF server any less valuable, nor the players on it. It's just a different type of game play.

I do concede that I read the regex wrong. Doesn't change the fact that one of my moderators is considered a low value player and the rankings reflect this.  So only a month's work has to be changed instead of two. 

The minetest client already puts joined servers at the top so why change the list? The players that we (or at least I) care the most about are those who support whatever play style the server was designed for.

As far as useless players:

>Peresmeshnik               1
andrewsonic83              1
2                          1
jon123                     1
vampiro                    1
171717                     1
axelromero                 1
banessaes                  1
Mavi                       1
Grigaliunas246             1
Margarita                  1
hbjunk                     1
CAMc                       1
kim                        1
fhfdhd                     1

Those are the lowest 15 players that placed at least one block. They have a match rate at or below the top players. 

There is no reason that a server with 40+ people  currently logged in should show up lower than one with none.  That server is popular for a reason. I don't know why, I've never been there, but people seem to want to go there, so why hinder that?  I know as a rule there is disdain for comparisons with minecraft but it didn't become as popular as it is because of all the users being high value or really much of any value in many cases. Those great users come as a part of the whole. Most people aren't master builders. They may have friends who are. Counting any person as less valuable just because of a name pattern is not a long term viable solution.

**Comment by Ezhh** [comment]
> It will encourage servers to encourage their players to move to the official app, which helps the server.

@paramat Server owners should encourage use of the official app because it's better for their players, not due to issues with unfair ranking. Your argument also provides zero motivation for me, as a server owner, to try and make long term players who fit the pattern to switch app. Why? Two reasons:

1. Apple.
2. Those are now the names those players use. Even if they switch app, all their builds/protections are under the existing names and those names are what people know them by. They won't want to change them. Even if they switch app, odds are they'll keep the name. 

(Note: it's not even worth the attempt with short term players, because there's a constant new influx of them anyway. I do try regardless when they complain about missing features, but usually reason 1 applies and they can't use the official client anyway.)

Where does this leave us? It leaves us with servers getting penalised for circumstances beyond their control. Oh wait, let me be more specific - beyond their control if they want to keep an open and welcoming server that can cater to everyone.

I could just disallow certain names of course, thus gaining an unfair advantage in ranking. But it feels underhand and wrong to do that when they harm nothing (other than my server rank!). Some servers do it though. I don't want to point fingers, but it isn't right that an unfair advantage can be gained by forcing players to adjust the default names the apps give them. The app players are still there after all, just a little bit disguised.

**Comment by Minetest-One** [comment]
I think we all showed or are able to see what is the most matter: very lot and very useless,
not the mobile (even they have low cpu, gpu and mem capacity resulting in low view, sofar some more following aspects) as
the massive same name convention (name123 using), and just check a time on IhrFussels you will see these are massively using same IP as just others of the same convention. As I think more they are bots,
and also some criteria here are sooo old and outdated, my catching server End June 19 show exactly can have 141 gamer same time by still just lag 0.3 - more servers have more than 0.5 with just 10 gamer.
So please use real data, and adjust new knowledge as we have much powerful hardware as when mt started.

And at last: when everybody mean need to have own server as he think his concept (hardware, mods) is BETTER (what does this mean) they also have to accept - that he might be alone with his idea, so should not complain server with godd combination off all have most more gamer,a nd that gamer SURE are also lazy to scroll down all server and test them ... they ust first they get,

and as long also the real ping of the showed serverlist is FALSE, is a LIE - how you wanna keep gamer use nearby, and also get better feeling without distance lag !!! Here is the first BIG lie to avery client, that is followed by sure more failures as get mad, when this server with much green is so low, how the others might be then ...

failure over failure - keeping and old concept. = minetest will be gone
